import { firefox } from "playwright";
import { pathToFileURL } from "node:url";
const t=()=>Date.now();
let s=t();
const b=await firefox.launch(); console.log("launch",t()-s,"ms"); s=t();
const ctx=await b.newContext({viewport:{width:390,height:900},isMobile:true,javaScriptEnabled:false}); console.log("ctx",t()-s,"ms"); s=t();
const p=await ctx.newPage(); console.log("newPage",t()-s,"ms"); s=t();
await p.goto(pathToFileURL("dist/ashiyado/index.html").href,{waitUntil:"domcontentloaded"}); console.log("goto",t()-s,"ms"); s=t();
await p.evaluate(()=>Promise.race([document.fonts?.ready||1,new Promise(r=>setTimeout(r,3000))])); console.log("fontsready",t()-s,"ms"); s=t();
const n=await p.evaluate(()=>document.querySelectorAll('[data-el]').length); console.log("evaluate",t()-s,"ms n=",n);
await b.close(); console.log("done");
